// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ContextImportCost))]
    partial class ContextImportCostModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Persistence.Entities.FinancialCore.Country", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"));

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Key");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.FinancialCore.Currency", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"));

                    b.Property<bool>("IsLocalCurrency")
                        .HasColumnType("bit");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Key");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.FinancialCore.ExchangeRate", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"));

                    b.Property<int>("DestinationCurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RateValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SourceCurrencyId")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Key");

                    b.HasIndex("DestinationCurrencyId");

                    b.HasIndex("SourceCurrencyId", "DestinationCurrencyId", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("ExchangeRates", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.FinancialCore.TaxConfiguration", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"));

                    b.Property<decimal>("CustomsServiceRatePercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GeneralItbisPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Key");

                    b.ToTable("TaxConfigurations", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.ImportationOrderAndLandCost.ImportationExpense", b =>
                {
                    b.Property<string>("ImportationExpenseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("DistributionMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ExpenseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportationExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImportationOrderId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ImportationExpenseId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ImportationOrderId");

                    b.ToTable("ImportationExpenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImportationExpenses_ExpenseAmount", "ExpenseAmount > 0");
                        });
                });

            modelBuilder.Entity("Persistence.Entities.ImportationOrderAndLandCost.ImportationOrder", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                 

                    b.Property<int>("ImporterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginCountryId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("TransportMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("CurrencyId");

                  

                    b.HasIndex("ImporterId");

                    b.HasIndex("OriginCountryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ImportationOrders", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.ImportationOrderAndLandCost.ImportationOrderDetail", b =>
                {
                    b.Property<string>("OrderDetailId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ExpectedProfitMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FOBUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ImportationOrderDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImportationOrderDetails_ExpectedProfitMargin", "ExpectedProfitMargin >= 0 and ExpectedProfitMargin < 100");

                            t.HasCheckConstraint("CK_ImportationOrderDetails_FOBUnitPrice", "FOBUnitPrice > 0");

                            t.HasCheckConstraint("CK_ImportationOrderDetails_Quantity", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("Persistence.Entities.ImportationOrderAndLandCost.LandedCostDetail", b =>
                {
                    b.Property<string>("LandedCostDetailId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("AssignedFreight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AssignedInsurance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AssignedLocalExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustomsServiceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DesiredMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Itbis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LandedCostSummaryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("LocalFob")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OriginalFOB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SelectiveTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SuggestedSalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tariff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalImportedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitImportedCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LandedCostDetailId");

                    b.HasIndex("LandedCostSummaryId");

                    b.HasIndex("ProductId");

                    b.ToTable("LandedCostDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_LandedCostDetails_Quantity", "Quantity > 0");

                            t.HasCheckConstraint("CK_LandedCostDetails_UnitImportedCost", "UnitImportedCost > 0");
                        });
                });

            modelBuilder.Entity("Persistence.Entities.ImportationOrderAndLandCost.LandedCostSummary", b =>
                {
                    b.Property<string>("LandedCostSummaryId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("LocalCurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("LocalTotalFob")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("OriginalTotalFob")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCif")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCustomsServiceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFreight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalImportationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalImportedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalInsurance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalItbis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLocalExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSelectiveTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTariff")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LandedCostSummaryId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("LandedCostSummaries", null, t =>
                        {
                            t.HasCheckConstraint("CK_LandedCostSummaries_OriginalTotalFob", "OriginalTotalFob > 0");

                            t.HasCheckConstraint("CK_LandedCostSummaries_TotalImportationCost", "TotalImportationCost > 0");
                        });
                });

            modelBuilder.Entity("Persistence.Entities.OperationalCommercial.Importers", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("countryId")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("countryId");

                    b.ToTable("Importers", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.OperationalCommercial.Products", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"));

                    b.Property<decimal?>("Broad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodeRefence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Large")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("countryId")
                        .HasColumnType("int");

                    b.Property<string>("tarrifCategoriesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Key");

                    b.HasIndex("countryId");

                    b.HasIndex("tarrifCategoriesId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.OperationalCommercial.Suppliers", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MainCurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("countryId")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("MainCurrencyId");

                    b.HasIndex("countryId");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.OperationalCommercial.TariffCategories", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("ITBIS")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PorcentageTariff")
                        .HasMaxLength(100)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PorcentageTaxSelective")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SelectiveTaxApplies")
                        .HasColumnType("bit");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Key");

                    b.ToTable("TariffCategories", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.FinancialCore.ExchangeRate", b =>
                {
                    b.HasOne("Persistence.Entities.FinancialCore.Currency", "DestinationCurrency")
                        .WithMany("ExchangeRatesDestination")
                        .HasForeignKey("DestinationCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Persistence.Entities.FinancialCore.Currency", "SourceCurrency")
                        .WithMany("ExchangeRatesSource")
                        .HasForeignKey("SourceCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationCurrency");

                    b.Navigation("SourceCurrency");
                });

            modelBuilder.Entity("Persistence.Entities.ImportationOrderAndLandCost.ImportationExpense", b =>
                {
                    b.HasOne("Persistence.Entities.FinancialCore.Currency", "Currency")
                        .WithMany("ImportationExpenses")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Entities.ImportationOrderAndLandCost.ImportationOrder", "ImportationOrder")
                        .WithMany("ImportationExpenses")
                        .HasForeignKey("ImportationOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("ImportationOrder");
                });

            modelBuilder.Entity("Persistence.Entities.ImportationOrderAndLandCost.ImportationOrder", b =>
                {
                    b.HasOne("Persistence.Entities.FinancialCore.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                

                    b.HasOne("Persistence.Entities.OperationalCommercial.Importers", "Importer")
                        .WithMany()
                        .HasForeignKey("ImporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Entities.FinancialCore.Country", "Country")
                        .WithMany()
                        .HasForeignKey("OriginCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Entities.OperationalCommercial.Suppliers", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Currency");

                    b.Navigation("Importer");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Persistence.Entities.ImportationOrderAndLandCost.ImportationOrderDetail", b =>
                {
                    b.HasOne("Persistence.Entities.ImportationOrderAndLandCost.ImportationOrder", "ImportationOrder")
                        .WithMany("ImportationOrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Entities.OperationalCommercial.Products", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportationOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Persistence.Entities.ImportationOrderAndLandCost.LandedCostDetail", b =>
                {
                    b.HasOne("Persistence.Entities.ImportationOrderAndLandCost.LandedCostSummary", "LandedCostSummary")
                        .WithMany("LandedCostDetails")
                        .HasForeignKey("LandedCostSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Entities.OperationalCommercial.Products", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandedCostSummary");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Persistence.Entities.ImportationOrderAndLandCost.LandedCostSummary", b =>
                {
                    b.HasOne("Persistence.Entities.ImportationOrderAndLandCost.ImportationOrder", "ImportationOrder")
                        .WithOne("LandedCostSummary")
                        .HasForeignKey("Persistence.Entities.ImportationOrderAndLandCost.LandedCostSummary", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportationOrder");
                });

            modelBuilder.Entity("Persistence.Entities.OperationalCommercial.Importers", b =>
                {
                    b.HasOne("Persistence.Entities.FinancialCore.Country", "country")
                        .WithMany("Importers")
                        .HasForeignKey("countryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");
                });

            modelBuilder.Entity("Persistence.Entities.OperationalCommercial.Products", b =>
                {
                    b.HasOne("Persistence.Entities.FinancialCore.Country", "country")
                        .WithMany("Products")
                        .HasForeignKey("countryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Entities.OperationalCommercial.TariffCategories", "tariffCategories")
                        .WithMany("Products")
                        .HasForeignKey("tarrifCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");

                    b.Navigation("tariffCategories");
                });

            modelBuilder.Entity("Persistence.Entities.OperationalCommercial.Suppliers", b =>
                {
                    b.HasOne("Persistence.Entities.FinancialCore.Currency", "MainCurrency")
                        .WithMany("Suppliers")
                        .HasForeignKey("MainCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Entities.FinancialCore.Country", "Country")
                        .WithMany("Suppliers")
                        .HasForeignKey("countryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("MainCurrency");
                });

            modelBuilder.Entity("Persistence.Entities.FinancialCore.Country", b =>
                {
                    b.Navigation("Importers");

                    b.Navigation("Products");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("Persistence.Entities.FinancialCore.Currency", b =>
                {
                    b.Navigation("ExchangeRatesDestination");

                    b.Navigation("ExchangeRatesSource");

                    b.Navigation("ImportationExpenses");

                    b.Navigation("ImportationOrders");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("Persistence.Entities.ImportationOrderAndLandCost.ImportationOrder", b =>
                {
                    b.Navigation("ImportationExpenses");

                    b.Navigation("ImportationOrderDetails");

                    b.Navigation("LandedCostSummary")
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.Entities.ImportationOrderAndLandCost.LandedCostSummary", b =>
                {
                    b.Navigation("LandedCostDetails");
                });

            modelBuilder.Entity("Persistence.Entities.OperationalCommercial.TariffCategories", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
